#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    if [ -x /usr/bin/cpp ]; then
        xrdb -merge $sysresources
    else
        xrdb -nocpp -merge $sysresources
    fi
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    if [ -x /usr/bin/cpp ]; then
        xrdb -merge "$userresources"
    else
        xrdb -nocpp -merge "$userresources"
    fi
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

[ -f /etc/xprofile ] && . /etc/xprofile
[ -f ~/.xprofile ] && . ~/.xprofile

export XDG_RUNTIME_DIR="/run/user/$UID"
export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus"

session=${1:-"dusk"}

case $session in
"dusk")
    /usr/lib/polkit-kde-authentication-agent-1 &
    ~/.fehbg &
    CM_IGNORE_WINDOW="[Kk]ee[Pp]ass[Xx][Cc]" clipmenud &
    numlockx &
    picom -b &
    qbittorrent &
    sxhkd -m 1 &
    udiskie -s &
    unclutter -b &
    st newsboat &
    xidlehook --not-when-audio --not-when-fullscreen \
        --timer 600 'betterlockscreen --lock' '' &
    exec dusk
    ;;
"awesome")
    /usr/lib/polkit-kde-authentication-agent-1 &
    clipmenud &
    numlockx &
    xidlehook --not-when-audio --not-when-fullscreen \
        --timer 600 'betterlockscreen --lock' '' &
    exec awesome
    ;;
esac
