[manager]
prepend_keymap = [
	# relative-motions keymaps
	{ on = [ "1" ], run = "plugin relative-motions 1", desc = "Move in relative steps" },
	{ on = [ "2" ], run = "plugin relative-motions 2", desc = "Move in relative steps" },
	{ on = [ "3" ], run = "plugin relative-motions 3", desc = "Move in relative steps" },
	{ on = [ "4" ], run = "plugin relative-motions 4", desc = "Move in relative steps" },
	{ on = [ "5" ], run = "plugin relative-motions 5", desc = "Move in relative steps" },
	{ on = [ "6" ], run = "plugin relative-motions 6", desc = "Move in relative steps" },
	{ on = [ "7" ], run = "plugin relative-motions 7", desc = "Move in relative steps" },
	{ on = [ "8" ], run = "plugin relative-motions 8", desc = "Move in relative steps" },
	{ on = [ "9" ], run = "plugin relative-motions 9", desc = "Move in relative steps" },
	{ on = [ "b", "g" ], run = [ '''
		shell 'case $(file --mime-type -Lb $0) in
					image/*) feh --bg-fill $0 ;;
					*) false ;;
				esac' --confirm
	''' ], desc = "Set desktop background" },
	{ on = [ "b", "l" ], run = [ '''
		shell 'case $(file --mime-type -Lb $0) in
				image/*) betterlockscreen -u $0 ;;
				*) false ;;
				esac' --confirm
		''' ], desc = "Set lockscreen background" },
	{ on = [ "s", "d" ], run = "plugin fzf", desc = "Jump to a file/directory via fzf" },
	{ on = [ "s", "s" ], run = "plugin zoxide", desc = "Jump to a directory via zoxide" },
	{ on = [ "s", "f" ], run = "search --via=fd", desc = "Search files by name via fd" },
	{ on = [ "s", "g" ], run = "search --via=rg", desc = "Search files by content via ripgrep" },
]
