[flavor]
dark = "tokyo-night-storm"
light = "tokyo-night-day"

[mgr]
find_keyword  = { fg = "#24283b", bg = "#ff9e64", bold = true }
border_symbol = " "

[indicator]
parent  = { reversed = true, bold = true }
current = { reversed = true, bold = true }
preview = { underline = false, reversed = true, bold = true }
padding = { open = "█", close = "█" }

[status]
overall   = { fg = "#c0caf5", bg = "#292E42" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

[filetype]
rules = [
	# Special files
	{ url = "*",  is = "orphan", fg = "red",     bold = true },
	{ url = "*",  is = "exec",   fg = "green",   bold = true },
	{ url = "*",  is = "link",   fg = "cyan",    bold = true },
	{ url = "*/", is = "link",   fg = "cyan",    bold = true },
	{ mime = "{image,video}/*",  fg = "magenta", bold = true },
	{ mime = "{audio}/*",        fg = "cyan" },

	# Fallback
	{ url = "*/", fg = "#7aa2f7", bold = true },
	{ url = "*", fg = "#c0caf5" }
]
