[mgr]
ratio = [2, 3, 3]
sort_by = "natural"
linemode = "size"
show_hidden = true
scrolloff = 10

[opener]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
open_browser = [
	{ run = 'chromium "$@"', desc = "Open in browser" },
]
edit = [
	{ run = 'nvim "$@"', block = true, desc = "Edit" },
]
edit_image = [
	{ run = 'krita "$@"', desc = "Edit image" },
]

[open]
prepend_rules = [
	{ name = "*.html", use = [ "edit", "open_browser" ] },
	{ name = "*.pdf", use = [ "open", "open_browser" ] },
	{ mime = "image/*", use = [ "open", "edit_image", "open_browser" ] },
]

[preview]
tab_size = 4
image_filter = "catmull-rom"
image_quality = 50
wrap = "yes"
image_delay = 100
