format = """$username$directory$git_branch$cmd_duration
$character"""

add_newline = true

[username]
style_user = "purple bold"
disabled = false
show_always = true

[directory]
style = "bold blue"
read_only = " 󰌾"

[line_break]
disabled = true

[git_branch]
symbol = " "
style= "bold yellow"
